version: "3"
  
services:
  db:
    container_name: 'user-db'
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports: 
      - "5432:5432"
  web:
    container_name: 'user-api'
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports: 
      - "8001:8001"
    depends_on:
      - db
  